// English -> Spanish for every translatable UI string in the resident app.
// English is the source; keys are the exact literals passed to the translate
// helper (useT). Strings with no entry fall back to English. Proper nouns
// (San Antonio, provider names, street names, person names, emails) are not
// translated and so are absent here.

export const strings_es: Record<string, string> = {
  // home
  "All of San Antonio, in one place.": "Todo San Antonio, en un solo lugar.",
  "Alerts near you": "Alertas cerca de ti",
  "Jump to": "Ir a",
  "Power status": "Estado de la energía",
  "Utility": "Servicios",
  "Report a problem": "Reportar un problema",
  "City · 311": "Ciudad · 311",
  "Bills & usage": "Facturas y consumo",
  "Local businesses": "Negocios locales",
  "Discover": "Descubrir",
  "My area": "Mi zona",
  "City": "Ciudad",
  "Profile & settings": "Perfil y ajustes",
  "You": "Tú",

  // save button
  "Saving…": "Guardando…",
  "Saved ✓": "Guardado ✓",
  "try again": "intentar de nuevo",
  "Couldn't save. Check your connection and try again.": "No se pudo guardar. Revisa tu conexión e inténtalo de nuevo.",

  // profile
  "Home": "Inicio",
  "Profile": "Perfil",
  "Your address determines which city services, schedules, and alerts AssistantSA shows you.": "Tu dirección determina qué servicios municipales, horarios y alertas te muestra AssistantSA.",
  "Service address": "Dirección de servicio",
  "Street address": "Dirección",
  "ZIP code": "Código postal",
  "Save address": "Guardar dirección",
  "Contact": "Contacto",
  "Name": "Nombre",
  "Email": "Correo electrónico",
  "Phone": "Teléfono",
  "Save contact": "Guardar contacto",
  "Preferences": "Preferencias",
  "Language and notifications": "Idioma y notificaciones",

  // preferences
  "Set your language and which notifications you receive.": "Configura tu idioma y qué notificaciones recibes.",
  "Language": "Idioma",
  "English": "Inglés",
  "Notifications": "Notificaciones",
  "Notifications are turned off for AssistantSA. Enable them in your device Settings to receive alerts.": "Las notificaciones están desactivadas para AssistantSA. Actívalas en los ajustes de tu dispositivo para recibir alertas.",
  "Utility alerts": "Alertas de servicios públicos",
  "Outages and utility service alerts at your address.": "Cortes y alertas de servicios públicos en tu dirección.",
  "City alerts": "Alertas de la ciudad",
  "Civic alerts that affect your area.": "Alertas cívicas que afectan tu zona.",
  "Event reminders": "Recordatorios de eventos",
  "A reminder before local events.": "Un recordatorio antes de eventos locales.",
  "Bill due reminders": "Recordatorios de vencimiento de facturas",
  "A reminder one day before a utility bill is due.": "Un recordatorio un día antes de que venza una factura de servicios.",
  "Voice": "Voz",
  "Choose the assistant's voice.": "Elige la voz del asistente.",
  "Male": "Hombre",
  "Female": "Mujer",
  "Compress voice data": "Comprimir datos de voz",
  "Uses less data on the assistant's voice. Helps when your connection is weak or spotty.": "Usa menos datos en la voz del asistente. Ayuda cuando tu conexión es débil o inestable.",

  // tab bar
  "Ask": "Preguntar",

  // civic
  "Alerts": "Alertas",
  "Current alerts from the city.": "Alertas actuales de la ciudad.",
  "Current alerts from the city": "Alertas actuales de la ciudad",
  "Source": "Fuente",
  "Events": "Eventos",
  "City events near you, published by San Antonio.": "Eventos de la ciudad cerca de ti, publicados por San Antonio.",
  "City events calendar": "Calendario de eventos de la ciudad",
  "When": "Cuándo",
  "Where": "Dónde",
  "Trash & recycling": "Basura y reciclaje",
  "Collection days for": "Días de recolección para",
  ", from Solid Waste Management.": ", de Gestión de Residuos Sólidos.",
  "Collection days from Solid Waste Management.": "Días de recolección de Gestión de Residuos Sólidos.",
  "Your collection days by address": "Tus días de recolección por dirección",
  "Day": "Día",
  "Next pickup": "Próxima recolección",
  "Status, alerts, events, and who to contact in San Antonio.": "Estado, alertas, eventos y a quién contactar en San Antonio.",
  "Departments": "Departamentos",
  "Every City department and office": "Todos los departamentos y oficinas de la ciudad",
  "Reps, police, schools, and more for your address": "Representantes, policía, escuelas y más para tu dirección",
  "Report a problem to the city": "Reportar un problema a la ciudad",
  "Unavailable": "No disponible",
  "Everything tied to": "Todo lo relacionado con",
  "Everything tied to your profile address.": "Todo lo relacionado con la dirección de tu perfil.",
  "Find my rep": "Encontrar a mi representante",
  "Who represents": "Quién representa a",
  "Who represents you. Based on your profile address.": "Quién te representa. Según la dirección de tu perfil.",
  "Based on your profile address.": "Según la dirección de tu perfil.",
  "Mayor, council member, and trustee": "Alcalde, concejal y miembro de la junta escolar",
  "Police substation": "Subestación de policía",
  "SAPD patrol substation serving you": "Subestación de patrulla del SAPD que te atiende",
  "Fire response area": "Área de respuesta de bomberos",
  "SAFD area of responsibility serving you": "Área de responsabilidad del SAFD que te atiende",
  "School district": "Distrito escolar",
  "Your assigned district and schools": "Tu distrito y escuelas asignadas",
  "Neighborhood association": "Asociación de vecinos",
  "The registered association for your address": "La asociación registrada para tu dirección",
  "District": "Distrito",
  "Title": "Cargo",
  "Schools": "Escuelas",
  "Neighborhood": "Vecindario",
  "Drawn from your address,": "Basado en tu dirección,",
  "Drawn from your profile address.": "Basado en la dirección de tu perfil.",
  "Boundary": "Límite",
  "For emergencies call 911.": "Para emergencias llama al 911.",

  // departments / discovery (static)
  "The City departments residents reach for most. Ask AssistantSA to find any other.": "Los departamentos de la Ciudad que los residentes consultan con más frecuencia. Pídele a AssistantSA que encuentre cualquier otro.",
  "311 Customer Service": "Servicio al Cliente 311",
  "Find information and get help with City services such as trash pickup or pothole repair.": "Encuentra información y obtén ayuda con los servicios de la Ciudad, como la recolección de basura o la reparación de baches.",
  "Solid Waste Management": "Gestión de Residuos Sólidos",
  "Garbage and recycling collection, as well as brush and bulk waste service.": "Recolección de basura y reciclaje, así como servicio de maleza y desechos voluminosos.",
  "Animal Care Services": "Servicios de Cuidado Animal",
  "Animal control and pet adoption services. Adopt, foster, or report.": "Servicios de control animal y adopción de mascotas. Adopta, acoge o reporta.",
  "Public Works": "Obras Públicas",
  "Builds and repairs City streets, drains and street signs.": "Construye y repara las calles, drenajes y señales de tránsito de la Ciudad.",
  "Parks & Recreation": "Parques y Recreación",
  "Maintains City parks and facilities. Reserve a park facility.": "Mantiene los parques e instalaciones de la Ciudad. Reserva una instalación de parque.",
  "Library": "Biblioteca",
  "The San Antonio Public Library system. Books, eBooks, Wi-Fi access.": "El sistema de la Biblioteca Pública de San Antonio. Libros, libros electrónicos y acceso a Wi-Fi.",
  "Development Services": "Servicios de Desarrollo",
  "Manages land and building development. Apply for permits or licenses.": "Gestiona el desarrollo de terrenos y construcciones. Solicita permisos o licencias.",
  "Metropolitan Health District": "Distrito Metropolitano de Salud",
  "Health services and programs. Restaurant inspections and food permits.": "Servicios y programas de salud. Inspecciones de restaurantes y permisos de alimentos.",
  "Municipal Court": "Corte Municipal",
  "Hears cases for minor offenses, including tickets and parking.": "Atiende casos por infracciones menores, incluyendo multas y estacionamiento.",
  "Police": "Policía",
  "The San Antonio Police Department, primary law enforcement agency.": "El Departamento de Policía de San Antonio, principal agencia de seguridad pública.",
  "Fire": "Bomberos",
  "Fire and emergency services. Fire codes and safety information.": "Servicios de bomberos y emergencias. Códigos contra incendios e información de seguridad.",
  "Neighborhood & Housing Services": "Servicios de Vecindario y Vivienda",
  "Rental and housing help, homeownership, and eviction resources.": "Ayuda con alquiler y vivienda, propiedad de vivienda y recursos contra el desalojo.",
  "Human Services": "Servicios Humanos",
  "Financial and social services for residents in need.": "Servicios financieros y sociales para residentes necesitados.",
  "Emergency Management": "Gestión de Emergencias",
  "Responds to emergencies and disasters. Sign up for AlertSA.": "Responde a emergencias y desastres. Regístrate en AlertSA.",
  "Mayor & City Council": "Alcalde y Concejo Municipal",
  "Find your councilmember. View agendas and public meetings.": "Encuentra a tu concejal. Consulta agendas y reuniones públicas.",
  "Report to 311": "Reportar al 311",
  "Report a problem to the city.": "Reporta un problema a la ciudad.",
  "This feature is blocked pending access to an external dependency.": "Esta función está bloqueada en espera de acceso a una dependencia externa.",
  "Filing a 311 report needs backend access to the city's 311 system. Until San Antonio grants that access, AssistantSA can't capture or submit reports here.": "Presentar un reporte 311 requiere acceso del backend al sistema 311 de la ciudad. Hasta que San Antonio otorgue ese acceso, AssistantSA no puede capturar ni enviar reportes aquí.",
  "Local businesses in your city.": "Negocios locales en tu ciudad.",
  "plumber open now": "plomero abierto ahora",

  // utility
  "Utilities": "Servicios",
  "Your bills, usage, and linked accounts.": "Tus facturas, consumo y cuentas vinculadas.",
  "Bills": "Facturas",
  "Your utility bills": "Tus facturas de servicios",
  "Usage": "Consumo",
  "What you have used": "Lo que has consumido",
  "Accounts": "Cuentas",
  "Link your utility accounts": "Vincula tus cuentas de servicios",
  "Outages at your address, from CPS Energy": "Cortes en tu dirección, de CPS Energy",
  "Your bills": "Tus facturas",
  "Your linked utility accounts.": "Tus cuentas de servicios vinculadas.",
  "Due date": "Fecha de vencimiento",
  "Statement": "Estado de cuenta",
  "Paying bills in AssistantSA is blocked pending an external dependency.": "El pago de facturas en AssistantSA está bloqueado a la espera de una dependencia externa.",
  "AssistantSA reads your bill, but can't pay it yet. Paying needs the utility's own payment flow or their opt-in. For now, open your provider's site to pay.": "AssistantSA lee tu factura, pero todavía no puede pagarla. El pago requiere el propio flujo de pago del proveedor de servicios o su autorización. Por ahora, abre el sitio de tu proveedor para pagar.",
  "Your usage": "Tu consumo",
  "What you have used, from your utility accounts.": "Lo que has consumido, de tus cuentas de servicios.",
  "From": "Desde",
  "To": "Hasta",
  "Outage status for": "Estado de cortes para",
  ", from CPS Energy.": ", de CPS Energy.",
  "Outage status from CPS Energy.": "Estado de cortes de CPS Energy.",
  "No address saved.": "No hay dirección guardada.",
  "Save your address to see outage and power status here.": "Guarda tu dirección para ver el estado de cortes y de la energía aquí.",
  "Power is on": "La energía está activa",
  "No outage reported at your address.": "No se reportan cortes en tu dirección.",
  "Address": "Dirección",
  "Reported": "Reportado",
  "Utility accounts": "Cuentas de servicios",
  "Link a provider so AssistantSA can read your bills and usage.": "Vincula un proveedor para que AssistantSA pueda leer tus facturas y tu consumo.",
  "Account": "Cuenta",
  "Status": "Estado",
  "Connected": "Conectada",
  "Unlink": "Desvincular",
  "Couldn't unlink. Check your connection and try again.": "No se pudo desvincular. Revisa tu conexión e inténtalo de nuevo.",
  "Link a new account": "Vincular una cuenta nueva",
  "Provider name": "Nombre del proveedor",
  "Select a provider": "Selecciona un proveedor",
  "Couldn't link the account. Check your connection and try again.": "No se pudo vincular la cuenta. Revisa tu conexión e inténtalo de nuevo.",
  "Enter a provider name and sign-in URL to continue. Your username and password stay encrypted on this phone and never leave it.": "Ingresa el nombre del proveedor y la URL de inicio de sesión para continuar. Tu usuario y contraseña permanecen cifrados en este teléfono y nunca salen de él.",

  // assistant
  "Your city, handled.": "Tu ciudad, resuelta.",
  "Stop hands-free voice": "Detener voz manos libres",
  "Start hands-free voice": "Iniciar voz manos libres",
  "Listening": "Escuchando",
  "Ask the assistant anything.": "Pregúntale lo que quieras al asistente.",
  "Send message": "Enviar mensaje",
  "Send": "Enviar",
  "[voice unavailable]": "[voz no disponible]",
  "Ask anything. Set reminders.": "Pregunta lo que sea. Programa recordatorios.",
  "Voice on": "Voz activada",
  "Voice off": "Voz desactivada",
  "Can't do that": "No puedo hacer eso",

  // bex concept — tab bar + wake bar
  "Chat": "Chat",
  "Feed": "Feed",
  "Settings": "Ajustes",
  "Bex is listening · ": "Bex está escuchando · ",
  "Wake word muted · ": "Palabra de activación silenciada · ",
  "tap to resume": "toca para reanudar",
  "Mute": "Silenciar",
  "Unmute": "Activar",

  // bex concept — feed
  "Reminders & alerts": "Recordatorios y alertas",
  "Delivered alerts and reminders, plus what's scheduled ahead.": "Alertas y recordatorios entregados, además de lo programado.",
  "Triggered": "Activados",
  "Upcoming": "Próximos",
  "Clear all": "Borrar todo",
  "Nothing scheduled": "Nada programado",
  "You're all caught up": "Estás al día",
  "Ask Bex to remind you about anything.": "Pídele a Bex que te recuerde cualquier cosa.",
  "New reminders and alerts land here.": "Los nuevos recordatorios y alertas aparecen aquí.",
  "scheduled": "programado",
  "item": "elemento",
  "items": "elementos",
  "Alert": "Alerta",
  "Reminder · you asked": "Recordatorio · lo pediste",
  "Dismissed": "Descartado",
  "Dismissed 1 item": "1 elemento descartado",
  "Undo": "Deshacer",
  "Health & safety": "Salud y seguridad",
  "I've read this": "Lo he leído",

  // bex concept — accounts
  "Linked services": "Servicios vinculados",
  "Link a utility and Bex can read bills, usage, and outages for you.": "Vincula un servicio y Bex podrá leer tus facturas, consumo y cortes.",
  "Add an account": "Agregar una cuenta",
  "Bex only reads what you link. Nothing is shared.": "Bex solo lee lo que vinculas. No se comparte nada.",
  "New account": "Cuenta nueva",
  "Add account": "Agregar cuenta",
  "Choose your provider and sign in. Bex uses it to fetch your data.": "Elige tu proveedor e inicia sesión. Bex lo usa para obtener tus datos.",
  "Provider": "Proveedor",
  "Credentials are stored encrypted on your device.": "Las credenciales se almacenan cifradas en tu dispositivo.",

  // bex concept — settings
  "Tune how Bex talks, listens, and notifies you.": "Ajusta cómo Bex habla, escucha y te notifica.",
  "City and utility alerts are scoped to this address.": "Las alertas de la ciudad y de servicios se limitan a esta dirección.",
  "Wake word": "Palabra de activación",
  "Listen for \"Hey Bex\" on every screen.": "Escucha \"Hey Bex\" en todas las pantallas.",
  "Bex's voice": "La voz de Bex",
  "Push notifications": "Notificaciones push",
  "Reminders and civic alerts when the app is closed.": "Recordatorios y alertas cívicas cuando la app está cerrada.",
  "Offline — showing saved data": "Sin conexión — mostrando datos guardados",
  "Something went wrong": "Algo salió mal",
  "Try again": "Reintentar",
  "Appearance": "Apariencia",
  "Dark theme": "Tema oscuro",
  "Use a darker color scheme.": "Usa un esquema de color más oscuro.",
};
