// Loads the whole-process config from process.env. A gitignored .env at the
// process working directory is loaded programmatically at startup when present;
// deployments that inject env vars directly (no .env file) skip the load.
// Non-secret numeric keys get sane defaults; secrets and source URLs are read
// as-is. Names match .env.example verbatim.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve as resolve_path } from "node:path";

import type {
    listen_address,
    scheduler_intervals,
    scrape_script_registry,
    server_config,
} from "./types.js";

// Read a required string env var, or a default. Empty string counts as unset.
function env_str(key: string, fallback?: string): string {
    const v = process.env[key];
    if (v === undefined || v === "") {
        if (fallback !== undefined) return fallback;
        return "";
    }
    return v;
}

// Read a numeric env var with a default. Non-numeric values fall back.
function env_num(key: string, fallback: number): number {
    const v = process.env[key];
    if (v === undefined || v === "") return fallback;
    const n = Number(v);
    return Number.isFinite(n) ? n : fallback;
}

// Build the scrape script registry from files. Each site is one file at
// ap-utility/scrape_scripts/<site_id>.js; the site_id is the file's base name.
// The login url is declared inside the file as a `// @url <url>` header line.
// Files with no @url header are skipped. No env var feeds this.
function build_scrape_script_registry(): scrape_script_registry {
    // ap-utility/scrape_scripts relative to this file (ap-server/dist).
    const here = dirname(fileURLToPath(import.meta.url));
    const scripts_dir = resolve_path(here, "../../ap-utility/scrape_scripts");

    let files: string[];
    try {
        files = readdirSync(scripts_dir).filter((f) => f.endsWith(".js"));
    } catch (err) {
        console.error(`[ap-server] scrape_scripts dir read failed at ${scripts_dir}:`, err);
        return {};
    }

    const registry: scrape_script_registry = {};
    for (const file of files) {
        const site_id = file.slice(0, -3);
        const script_path = resolve_path(scripts_dir, file);
        const script = readFileSync(script_path, "utf8");
        const match = script.match(/^\/\/\s*@url\s+(\S+)/m);
        if (!match) {
            console.error(`[ap-server] scrape script ${file} missing // @url header; skipped`);
            continue;
        }
        registry[site_id] = { url: match[1] ?? "", script };
    }
    return registry;
}

// Scheduler intervals are configured in minutes as float values; convert each to
// milliseconds (minutes * 60000) through this single converter before arming the
// timers, so no millisecond literals appear in config.
function minutes_to_ms(minutes: number): number {
    return minutes * 60000;
}

// Launch crawl-service from the venv setup creates. The interpreter path differs
// between Windows (.venv\Scripts) and Unix (.venv/bin); the command runs with cwd
// crawl-service, so the path stays relative.
function default_crawl_service_cmd(): string {
    return process.platform === "win32"
        ? ".venv\\Scripts\\python.exe crawl_service.py"
        : ".venv/bin/python crawl_service.py";
}

// Launch redis. Windows has no native redis-server; run it as a Docker container
// whose published port maps to the Windows host (Docker Desktop required). Linux
// and Codespaces use the binary on PATH directly. The port arg the caller appends
// is passed through to redis-server inside the container.
function default_redis_cmd(): string {
    return process.platform === "win32"
        ? "docker run --rm --name assistantsa-redis -p 6379:6379 redis"
        : "redis-server";
}

// Read the RS256 public key from backend/keys/public.pem (generated by
// scripts/generate_keys.mjs). This file runs from ap-server/dist, so the
// backend root is two levels up. Missing file -> empty, importSPKI then throws.
function read_public_key(): string {
    const here = dirname(fileURLToPath(import.meta.url));
    const key_path = resolve_path(here, "../../keys/public.pem");
    try {
        return readFileSync(key_path, "utf8");
    } catch (err) {
        console.error(`[ap-server] public key read failed at ${key_path}:`, err);
        return "";
    }
}

export function load_config(): server_config {
    // Load a repo-root .env into process.env when present. The server runs from
    // the repo root, so the file sits at the process working directory. Skipped
    // when absent (deployments inject env vars directly).
    const env_file_path = resolve_path(process.cwd(), ".env");
    if (existsSync(env_file_path)) {
        process.loadEnvFile(env_file_path);
    }

    const scheduler_intervals_value: scheduler_intervals = {
        collection_schedule_interval_ms: minutes_to_ms(
            env_num("scheduler_collection_schedule_interval_minutes", 4320),
        ),
        city_alerts_interval_ms: minutes_to_ms(
            env_num("scheduler_city_alerts_interval_minutes", 5),
        ),
        city_events_interval_ms: minutes_to_ms(
            env_num("scheduler_city_events_interval_minutes", 1440),
        ),
        power_outage_interval_ms: minutes_to_ms(
            env_num("scheduler_power_outage_interval_minutes", 5),
        ),
        bill_reminder_interval_ms: minutes_to_ms(
            env_num("scheduler_bill_reminder_interval_minutes", 1440),
        ),
        reminder_eval_interval_ms: minutes_to_ms(
            env_num("scheduler_reminder_eval_interval_minutes", 1),
        ),
    };

    return {
        server_listen_address: env_str("server_listen_address", "0.0.0.0:8080"),
        database_url: env_str("database_url"),
        token_verification_public_key: read_public_key(),

        claude_api_key: env_str("claude_api_key"),
        claude_chat_model: env_str("claude_chat_model", "claude-opus-4-8"),
        claude_voice_model: env_str("claude_voice_model", "claude-haiku-4-5"),
        claude_chat_max_tokens: env_num("claude_chat_max_tokens", 1024),
        claude_voice_max_tokens: env_num("claude_voice_max_tokens", 512),
        max_message_history: env_num("max_message_history", 30),
        redis_url: env_str("redis_url", "redis://localhost:6379"),
        redis_cmd: env_str("redis_cmd", default_redis_cmd()),

        find_my_rep_gis_url: env_str("find_my_rep_gis_url"),
        my_area_neighborhood_url: env_str("my_area_neighborhood_url"),
        my_area_school_url: env_str("my_area_school_url"),
        geocode_url: env_str("geocode_url", "https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer"),
        council_staff_source_url: env_str("council_staff_source_url"),
        collection_schedule_source_url: env_str("collection_schedule_source_url"),
        city_alerts_source_url: env_str("city_alerts_source_url"),
        nws_alerts_api_url: env_str("nws_alerts_api_url", "https://api.weather.gov/alerts"),
        city_events_source_url: env_str("city_events_source_url"),
        alerts_retention_days: env_num("alerts_retention_days", 30),
        events_retention_days: env_num("events_retention_days", 30),
        collection_schedule_refresh_days: env_num("collection_schedule_refresh_days", 30),
        my_area_refresh_days: env_num("my_area_refresh_days", 180),

        utility_retention_days: env_num("utility_retention_days", 30),
        power_outage_source_url: env_str("power_outage_source_url"),
        bill_due_reminder_days: env_num("bill_due_reminder_days", 5),
        scrape_script_registry: build_scrape_script_registry(),

        // ap-voice runs as a separate Rust process; the bridge proxies to it.
        ap_voice_ws_url: env_str("ap_voice_ws_url", "ws://localhost:8090/voice"),

        // crawl4ai Python sidecar for ap-civic page fetches; empty disables it and
        // the page_fetcher falls back to a raw GET.
        crawl_service_url: env_str("crawl_service_url", "http://127.0.0.1:8095"),

        // ap-server spawns the sidecars by default so one command brings the whole
        // backend up; set spawn_sidecars=false to run them externally.
        spawn_sidecars: env_str("spawn_sidecars", "true") !== "false",
        ap_voice_cmd: env_str("ap_voice_cmd", "cargo run --release"),
        // Default into the venv created by setup; path differs per OS.
        crawl_service_cmd: env_str("crawl_service_cmd", default_crawl_service_cmd()),

        scheduler_intervals: scheduler_intervals_value,

        // ap-civic's scheduled fetch reads this; ap-server also exports it into
        // process.env so the module's own env read resolves (see index.ts).
        scheduler_city_tenant_id: env_str("CIVIC_SCHEDULER_CITY_TENANT_ID"),
    };
}

// Split "host:port" into parts. Bare ":8080" binds all interfaces.
export function resolve_listen_address(value: string): listen_address {
    const idx = value.lastIndexOf(":");
    if (idx === -1) return { host: "0.0.0.0", port: 8080 };
    const host = value.slice(0, idx) || "0.0.0.0";
    const port = Number(value.slice(idx + 1)) || 8080;
    return { host, port };
}
